export const FETCH_COURSE_DETAIL = "FETCH_COURSE_DETAIL";
export const FETCH_COURSE = "FETCH_COURSE";
export const FETCH_CREDENTIALS = "FETCH_CREDENTIALS";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_COURSE_BY_CATEGORY = "FETCH_COURSE_BY_CATEGORY";
export const SEARCH_COURSE = "SEARCH_COURSE";
export const SELECTED_COURSE = "SELECTED_COURSE";
// export const SELECTED_COURSE_CATEGORY = "SELECTED_COURSE_CATEGORY";
